name: Build and Deploy Static Site

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  ZOLA_VERSION: "0.19.2"
  TEMPLATES_REPO: "netangel/solombala-shipyard-archive-site"
  SCRIPTS_REPO: "netangel/archive-tovarishestvo"
  S3_ENDPOINT: "se-sto-1.linodeobjects.com"
  S3_BUCKET: "schooner-archive-v2"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout JSON Data Repository
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout Zola Templates
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TEMPLATES_REPO }} 
          ssh-key: ${{ secrets.TEMPLATES_SSH_KEY }}
          path: template

      - name: Checkout PowerShell Scripts
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SCRIPTS_REPO }} 
          ssh-key: ${{ secrets.SCRIPTS_SSH_KEY }}
          path: scripts

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Install Zola
        run: |
          curl -L "https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" | tar xz
          sudo mv zola /usr/local/bin

      - name: Convert JSON to Zola Content
        shell: pwsh
        run: |
          . ./scripts/Convert-ToZola.ps1
          Convert-ToZola -SourcePath ./source -OutputPath ./template/content
      
      - name: Build Zola Site
        run: |
          cd template
          zola build

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.9.0
        with:
          provider: linode
          access_key: ${{ secrets.LINODE_BUCKET_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.LINODE_BUCKET_SECRET_ACCESS_KEY }}

      - name: Upload the zola site
        run: |
          s3cmd --host ${{ env.S3_ENDPOINT }} --acl-public --recursive --guess-mime-type sync .\template\public\ s3://${{ env.S3_BUCKET }}/
          s3cmd --host ${{ env.S3_ENDPOINT }} info s3://${{ env.S3_BUCKET }}/
